trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: Build
  displayName: 'Build Stage'

  jobs:

  - job: BuildJob
    displayName: 'Build Job'

    steps:

    - script: |
        echo "Build Started"
        ls -la
      displayName: 'Display Files'

    - task: CopyFiles@2
      inputs:
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy HTML and CSS Files'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'website'
        publishLocation: 'Container'
      displayName: 'Publish Artifact'

- stage: Deploy
  displayName: 'Deploy Stage'

  dependsOn: Build

  jobs:

  - deployment: DeployProd
    displayName: 'Deploy To Production'

    environment: prod

    strategy:
      runOnce:
        deploy:
          steps:

          - task: DownloadBuildArtifacts@0
            inputs:
              artifactName: 'website'
              downloadPath: '$(Pipeline.Workspace)'
            displayName: 'Download Artifact'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'azure-connection-lab'
              appName: 'sachin-devops-lab-786'
              package: '$(Pipeline.Workspace)/website'
            displayName: 'Deploy To Azure Web App'
