trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: Plan
  displayName: 'Terraform Plan Stage'

  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan Job'

    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - script: terraform version
      displayName: 'Check Terraform Version'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'terraform-azure-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: 'terraform'
        inlineScript: |
          terraform init
      displayName: 'Terraform Init'

    - script: terraform validate
      workingDirectory: terraform
      displayName: 'Terraform Validate'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'terraform-azure-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: 'terraform'
        inlineScript: |
          terraform plan -out=tfplan
      displayName: 'Terraform Plan'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'terraform/tfplan'
        artifact: 'tfplan'
      displayName: 'Publish Terraform Plan'


- stage: Apply
  displayName: 'Terraform Apply Stage'
  dependsOn: Plan

  jobs:
  - deployment: TerraformApply
    displayName: 'Terraform Apply Job'
    environment: terraform-prod

    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self
          
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: 'tfplan'
              path: '$(Pipeline.Workspace)/tfplan'
            displayName: 'Download Terraform Plan'

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'terraform-azure-connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              workingDirectory: 'terraform'
              inlineScript: |
                terraform init
                terraform apply -auto-approve $(Pipeline.Workspace)/tfplan/tfplan
            displayName: 'Terraform Apply'